Update collaboration.md
SenseNet/docs.sensenet.com pull request #188
Opened 2021-02-17 14:00 UTC by molnarm84

2021-02-18 07:41 UTC, huszerlbence commented on content/concepts/collaboration.md
> +In sensenet it is possible to make real-time editing together with your collaborators, thanks to **Office Online Editing**.  **Versioning** feature is the management of changes to documents and other
```suggestion
In sensenet it is possible to make real-time editing together with your collaborators, thanks to **Office Online Editing**. 
**Versioning** let's you track changes of documents and other information stored in the repository.
```

2021-02-18 07:43 UTC, huszerlbence commented on content/concepts/collaboration.md
> +Created around the concept “everything is content”, in sensenet it is easy to **share** not only a single content (like a document) but a whole folder or a workspace with other users.
```suggestion
sensenet let's you easily **share** not only a single content (like a document) but whole folders or workspace with other users.
```

2021-02-18 07:43 UTC, huszerlbence commented on content/concepts/collaboration.md
> +Using **simple approval**, contents needs to be sent for approval and can only be published when the review is finished and modification requests has been adapted.
```suggestion
With **simple approval** feature, contents needs to be sent for approval and can only be published when the review is finished and modification requests has been adapted.
```

2021-02-18 07:44 UTC, huszerlbence requested changes
suggested some changes, please check and approve if you agree

2021-02-26 07:38 UTC, herflis approved these changes

2021-02-26 12:29 UTC, huszerlbence approved these changes
szép munka

2021-02-26 15:05 UTC, merged