Update user-and-permission-management.md
SenseNet/docs.sensenet.com pull request #189
Opened 2021-02-17 14:46 UTC by molnarm84

2021-02-18 07:35 UTC, huszerlbence commented on content/concepts/user-and-permission-management.md
> +There are several situations when you have to adjust the rights of the users (when there are some changes in the company, e.g. someone leaves the company), and it is important to make it in a short t
```suggestion
There are several situations when you have to adjust user rights, someone leaves the company for example. In this case it is important to make it in a short time. 
```

2021-02-18 07:36 UTC, huszerlbence commented on content/concepts/user-and-permission-management.md
> +In Sensenet it is possible to set permissions on role-based or on document level too. There are several built-in goups and users, and also permissions in sensenet, however it is possible to create cu
```suggestion
In sensenet it is possible to set permissions base on roles or on document level too. There are several built-in goups and users, and also permissions in sensenet, however it is possible to create custom ones as well.
```

2021-02-18 07:36 UTC, huszerlbence commented on content/concepts/user-and-permission-management.md
> +As sensenet is built around the concept “everything is content” user management is very simple, and thanks to the tree structure you can take advantage of the permission inheritance during your work.
```suggestion
As sensenet is built around the concept “everything is content”, user management is very simple, and thanks to the tree structure you can take advantage of the permission inheritance during your work.
```

2021-02-18 07:36 UTC, huszerlbence requested changes
made some suggestions, check and approve if you agree

2021-02-25 13:30 UTC, molnarm84 commented on content/concepts/user-and-permission-management.md
> +In Sensenet it is possible to set permissions on role-based or on document level too. There are several built-in goups and users, and also permissions in sensenet, however it is possible to create cu
```suggestion
In sensenet it is possible to set permissions based on roles or on document level too. There are several built-in goups and users, and also permissions in sensenet, however it is possible to create custom ones as well.
```

2021-02-26 09:19 UTC, herflis approved these changes

2021-02-26 12:30 UTC, huszerlbence approved these changes

2021-02-26 15:05 UTC, merged