Picker
SenseNet/docs.sensenet.com pull request #193
Opened 2021-02-24 08:00 UTC by taki9

2021-02-24 18:05 UTC, huszerlbence requested changes
Made some minor changes. Please check and approve if you agree with them.

2021-02-24 18:05 UTC, huszerlbence commented on content/guides/content-management/picker.md
> +If you know exatly what you want to pick, you can search for the specific content using the search bar. This mode is activated by clicking inside the input. It searches in the DisplayName and Name fi
```suggestion
If you know exactly what you're looking for, you can search for a specific content using the **search** bar. This mode is activated by clicking the search input and gives results based on DisplayName and Name fields.

**Selection** view is activated when you click on the 'Show selection' link between the search input and the results.
This lists all selected items and you can also deleselect them.

```

2021-02-25 12:53 UTC, molnarm84 approved these changes

2021-02-26 12:32 UTC, huszerlbence approved these changes

2021-02-26 15:29 UTC, merged