Add initial version of gatsby+sensenet guide
SenseNet/docs.sensenet.com pull request #228
Opened 2021-05-18 12:36 UTC by herflis

2021-05-25 10:41 UTC, huszerlbence requested changes
fixed some stuff here and there but I can't really add more to this. I think it's good, laconic but good.

2021-05-25 10:41 UTC, huszerlbence commented on content/integrations/gatsby/using-gatsby-with-sensenet.md
> +sensenet is the single hub for all your content packed with enterprise grade features. In sensenet everything is a content (blog posts, files, users, roles, comments, etc.) delivered the same way thr
```suggestion
sensenet is the single hub for all your content, packed with enterprise grade features. In sensenet everything is a content (blog posts, files, users, roles, comments, etc.) delivered the same way through the API, making it super easy to work with any type of data. With the flexibility and power of sensenet and Gatsby you can build any kind of app or website you need.
```

2021-05-25 10:41 UTC, huszerlbence commented on content/integrations/gatsby/using-gatsby-with-sensenet.md
> +Cloud-based approach lets you forget about installation and operation tasks, all the subscriber repositories are on the same version and this allows us to deploy new features and patches for free, qu
```suggestion
Cloud-based approach lets you forget about installation and operation tasks, all the subscriber repositories are on the same version and this allows us to deploy new features and patches for quickly and efficiently to all of the customer repositories (for free) on a regular basis.
```

2021-05-25 10:41 UTC, huszerlbence commented on content/integrations/gatsby/using-gatsby-with-sensenet.md
> +1. Create a sensenet account to get a repository
```suggestion
1. [Create a sensenet account](https://profile.sensenet.com/?redirectToLogin) to get a repository
```

2021-05-25 10:41 UTC, huszerlbence commented on content/integrations/gatsby/using-gatsby-with-sensenet.md
> +- Storing massive amounts of data
```suggestion
- Storing massive amounts of data seurely
```

2021-05-26 07:49 UTC, molnarm84 approved these changes

2022-06-26 13:19 UTC, closed without merging